apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app.kubernetes.io/name: pyrra-api
  name: pyrra-api
  namespace: openshift-monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: pyrra-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pyrra-api
    spec:
      containers:
        - args:
            - api
            - --prometheus-url=https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
            - --api-url=http://pyrra-kubernetes.openshift-monitoring.svc.cluster.local:9444
            - --prometheus-bearer-token-path=/var/run/secrets/tokens/pyrra-kubernetes
          image: ghcr.io/pyrra-dev/pyrra:v0.6.1
          imagePullPolicy: IfNotPresent
          name: pyrra-api
          ports:
            - containerPort: 9099
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/tokens
              name: pyrra-sa-token
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: trusted-ca
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: pyrra-kubernetes
      volumes:
        - name: pyrra-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: pyrra-kubernetes
        - configMap:
            defaultMode: 420
            items:
              - key: service-ca.crt
                path: service-ca.crt
            name: openshift-service-ca.crt
          name: trusted-ca
