global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s

rule_files:
  - 'pyrra/*.yaml'

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
