---
apiVersion: v1
kind: Namespace
metadata:
  name: scorebylabel
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-scheduler-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - events
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - bindings
      - pods/binding
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources: ['*']
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
      - patch
      - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-scheduler-sa
  namespace: scorebylabel
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-scheduler-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-scheduler-clusterrole
subjects:
  - kind: ServiceAccount
    name: my-scheduler-sa
    namespace: scorebylabel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scorebylabel-scheduler-config
  namespace: scorebylabel
data:
  scorebylable-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: scorebylabel
        plugins:
          score:
            enabled:
              - name: ScoreByLabel
            disabled:
              - name: "*" # disable all default plugins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorebylabel-scheduler
  namespace: scorebylabel
  labels:
    app: scorebylabel-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scorebylabel-scheduler
  template:
    metadata:
      labels:
        app: scorebylabel-scheduler
    spec:
      serviceAccount: my-scheduler-sa
      volumes:
        - name: etckubernetes
          configMap:
            name: scorebylabel-scheduler-config
      containers:
        - name: kube-scheduler
          image: cr7258/my-scheduler:latest
          imagePullPolicy: Always
          args:
            - ./my-scheduler
            - --config=/etc/kubernetes/scorebylable-scheduler-config.yaml
            - -v=6
          volumeMounts:
            - name: etckubernetes
              mountPath: /etc/kubernetes