apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-svc-dropboxapi
spec:
  hosts:
  - api.dropboxapi.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
