apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  target: '99'
  window: 4w
  indicator:
    ratio:
      errors:
        metric: http_requests_total{job="thanos-query",handler=~"query|query_range",code=~"5.."}
      total:
        metric: http_requests_total{job="thanos-query",handler=~"query|query_range"}
