---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pyrra-kubernetes
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules/status
  verbs:
  - get
- apiGroups:
  - pyrra.dev
  resources:
  - servicelevelobjectives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pyrra.dev
  resources:
  - servicelevelobjectives/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources:
    - configmaps
  verbs:
    - create
    - get
    - list
    - update
    - watch
    - patch
