apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
type: Opaque
stringData:
      internal_users.yml: |-
        _meta:
          type: "internalusers"
          config_version: 2
        admin:
          hash: "$2a$12$UEPhgphoFf1kdeuzNFdowusZWgkn8.e1Vq6eYcY5EZWDRl2tusAzm"
          reserved: true
          backend_roles:
          - "admin"
          description: "Demo admin user"
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials-secret
type: Opaque
data:
  # admin
  username: YWRtaW4=
  # echo -n 'Tg9!eXr2@LmQ58z#' | base64
  password: VGc5IWVYcjJATG1RNTh6Iw==