[package]
name = "elasticsearch-example"
version = "0.1.0"
edition = "2024"

[dependencies]
elasticsearch = "9.0.0-alpha.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
