{
 "title": "Submariner Monitoring",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(up,cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "ServiceImport Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "submariner_service_import{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ServiceExport Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "submariner_service_export{cluster=\"$cluster\"} OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Node Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "submariner_gateways{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "submariner_connection_latency_seconds{cluster=\"$cluster\"}",
     "legendFormat": "{{remote_cluster}}    {{remote_hostname}}    {{remote_endpoint_ip}}"
    }
   ]
  },
  {
   "title": "Submariner Connections",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "submariner_connections{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submariner Gateway",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "submariner_gateway_rx_bytes{cluster=\"$cluster\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "submariner_gateway_tx_bytes{cluster=\"$cluster\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "submariner_connection_latency_seconds{cluster=\"$cluster\"} - 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lighthouse DNS Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "submariner_service_discovery_query{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}