apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
    - name: custom-gateway
      namespace: custom-ns-name
      enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: false