apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          datasourceUid: jaeger
          matcherRegex: trace_id
          matcherType: label
          url: $${__value.raw}
  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        customQuery: true
        tags:
          - key: service.name
            value: service_name
        query: '{$${__tags}} | trace_id="$${__span.traceId}"'
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: exported_job
        queries:
          - name: Request rate
            query: rate(http_server_duration_milliseconds_count{$$__tags}[5m])
