apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: coredns-request-latency
  namespace: monitoring
spec:
  description: ""
  indicator:
    latency:
      success:
        metric: coredns_dns_request_duration_seconds_bucket{job="coredns",le="0.032"}
      total:
        metric: coredns_dns_request_duration_seconds_count{job="coredns"}
  target: "99"
  window: 2w
