apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-http-errors
  namespace: monitoring
spec:
  description: ""
  indicator:
    ratio:
      errors:
        metric: prometheus_http_requests_total{job="prometheus-k8s",code=~"5.."}
      total:
        metric: prometheus_http_requests_total{job="prometheus-k8s"}
  target: "99.99"
  window: 2w
