[project]
name = "test-to-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.1",
    "smolagents>=1.9.2",
    "sqlalchemy>=2.0.38",
]
