[project]
name = "langchain-mcp-adapters-demo"
version = "0.1.0"
description = "Demo of LangChain MCP Adapters"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-mcp-adapters>=0.0.5",
    "langchain-openai>=0.3.9",
    "langgraph>=0.3.14",
    "mcp>=1.4.1",
]
